#!/bin/sh

die () {
   echo "*** mkconfig: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
EOF

echo "#define YALS_OS \"`uname -srmn`\""
echo "#define YALS_COMPILED \"`date`\""
#CUTHERE
echo "#define YALS_RELEASED \"`date`\""
echo "#define YALS_VERSION \"`cat VERSION`\""
echo "#define YALS_ID \"`./getgitid.sh`\""
